name: clone submodules

on:
  workflow_dispatch:
    inputs:
          logLevel:
            description: 'Log level'     
            required: true
            default: 'warning'
          tags:
            description: 'build scenario tag'  
            
permissions: write-all

jobs:
  clone-submodules:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v2
        with:
          repository: MichaelGrafnetter/DSInternals
          path: DSInternals
       
      - uses: actions/checkout@v2
        with:
          repository: sqlmapproject/sqlmap
          path: sqlmap
        
      - uses: actions/checkout@v2
        with:
          repository: SnaffCon/Snaffler
          path: Snaffler
         
      - uses: actions/checkout@v2
      - run: | 
          git config user.name liranpi2
          git submodule add https://github.com/MichaelGrafnetter/DSInternals.git DSInternals
          git submodule add https://github.com/sqlmapproject/sqlmap.git sqlmap
          git submodule add https://github.com/SnaffCon/Snaffler.git 
          git pull && git submodule foreach git pull origin master
          git add .
          git commit -am "add submodule" && git push || echo "No changes to commit"
        continue-on-error: true
